spring:
  config:
    activate:
      on-profile: "jpa-local"
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: info

---

spring:
  config:
    activate:
      on-profile: "jpa-real"
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
    show-sql: false
    database: mysql
    properties:
      hibernate:
        format_sql: false
    open-in-view: false

logging:
  level:
    org:
      hibernate:
        type: info
